version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: maumneto
      POSTGRES_PASSWORD: mau123
      POSTGRES_DB: mynestdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: mauricio.moreira@unichristus.edu.br
      PGADMIN_DEFAULT_PASSWORD: mau123
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
